name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - README.md
      #- .github/workflows/dockerhub-description.yml
  pull_request:
    branches:
      - main
    paths:
      - README.md
      #- .github/workflows/dockerhub-description.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Read short description from README.md
      id: readme
      run: echo "::set-output name=short-description::$(head -n 1 README.md)"

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: eyjo1/${{ vars.DOCKER_REPO }}
        #short-description: "PostgreSQL image with multiple databases and users and backup support."
        short-description: ${{ steps.readme.outputs.short-description }}
        enable-url-completion: true